import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-background': '#e5e1e6',
        'background': '#010102',
        'on-tertiary-fixed-variant': '#4c406a',
        'surface-variant': '#353438',
        'primary-fixed': '#eddcff',
        'on-secondary-fixed': '#1b1834',
        'on-secondary-fixed-variant': '#464362',
        'on-secondary-container': '#bdb7dd',
        'surface': '#131316',
        'surface-bright': '#39393c',
        'tertiary': '#cfbff0',
        'secondary-fixed': '#e4dfff',
        'primary-fixed-dim': '#d3beed',
        'inverse-primary': '#685780',
        'secondary-container': '#4b4867',
        'on-primary-container': '#f7ecff',
        'on-error-container': '#ffdad6',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-surface': '#e5e1e6',
        'surface-container-lowest': '#0e0e11',
        'surface-container-low': '#1c1b1f',
        'surface-container-high': '#2a292d',
        'surface-container': '#201f23',
        'secondary': '#c8c2e8',
        'inverse-on-surface': '#313034',
        'primary-container': '#77658f',
        'on-primary-fixed': '#231338',
        'inverse-surface': '#e5e1e6',
        'on-primary-fixed-variant': '#503f67',
        'on-secondary': '#302d4b',
        'tertiary-container': '#736692',
        'on-tertiary-container': '#f5ecff',
        'outline-variant': '#4a454d',
        'surface-dim': '#131316',
        'outline': '#958e98',
        'on-surface-variant': '#cbc4ce',
        'primary': '#d3beed',
        'surface-container-highest': '#353438',
        'tertiary-fixed': '#e9ddff',
        'tertiary-fixed-dim': '#cfbff0',
        'secondary-fixed-dim': '#c8c2e8',
        'surface-tint': '#d3beed',
        'on-tertiary-fixed': '#20143b',
        'on-primary': '#39294f',
        'error': '#ffb4ab',
        'on-tertiary': '#352952',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        '2xl': '1rem',
      },
      spacing: {
        'section-gap': '80px',
        'gutter': '24px',
        'base': '8px',
        'container-padding': '24px',
      },
      fontFamily: {
        'space': ['Space Grotesk', 'sans-serif'],
        'mono-code': ['JetBrains Mono', 'monospace'],
        'body': ['Inter', 'sans-serif'],
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 15px rgba(119, 101, 143, 0.3)' },
          '50%': { boxShadow: '0 0 30px rgba(119, 101, 143, 0.6)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'pulse-glow': 'pulse-glow 3s ease-in-out infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
export default config;
