import { Track, Competition, Achievement, Badge, DashboardStats, User } from './types';

export const NAV_LINKS = [
  { label: 'Home', href: '/' },
  { label: 'Tracks', href: '/tracks' },
  { label: 'Dashboard', href: '/dashboard' },
  { label: 'Leaderboard', href: '/leaderboard' },
  { label: 'Competitions', href: '/competitions' },
];

export const FEATURES = [
  {
    title: 'Dynamic Input Generator',
    description: 'Every user receives unique generated inputs for each challenge. Prevents cheating and ensures fair evaluation.',
    icon: 'Shuffle',
    gradient: 'from-violet-500 to-purple-500',
  },
  {
    title: 'Secure Code Execution',
    description: 'Your code runs in isolated Docker containers with strict CPU, memory, and time limits. No network access.',
    icon: 'Shield',
    gradient: 'from-emerald-500 to-teal-500',
  },
  {
    title: 'Real-time Leaderboards',
    description: 'Compete on global, track, and challenge leaderboards. Rankings based on XP, accuracy, speed, and streaks.',
    icon: 'Trophy',
    gradient: 'from-amber-500 to-orange-500',
  },
  {
    title: 'Achievement System',
    description: 'Earn badges, unlock achievements, and level up as you progress through challenges and competitions.',
    icon: 'Award',
    gradient: 'from-rose-500 to-pink-500',
  },
  {
    title: 'Learning Paths',
    description: 'Structured tracks guide you from basics to advanced. Each level unlocks only after mastering the previous.',
    icon: 'Route',
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    title: 'Competition Mode',
    description: 'Participate in weekly challenges, monthly contests, and live competitions with real-time rankings.',
    icon: 'Swords',
    gradient: 'from-red-500 to-rose-500',
  },
];

export const STATS = [
  { label: 'Active Users', value: '10,000+', icon: 'Users' },
  { label: 'Challenges Solved', value: '250,000+', icon: 'CheckCircle' },
  { label: 'Active Competitions', value: '24', icon: 'Zap' },
  { label: 'Learning Tracks', value: '15', icon: 'BookOpen' },
];

export const TRACKS: Track[] = [
  {
    id: '1',
    title: 'Arrays',
    slug: 'arrays',
    description: 'Master array manipulation, traversals, and transformations. From basic operations to advanced techniques.',
    icon: 'Layers',
    color: 'from-blue-500 to-cyan-500',
    difficulty: 'Beginner',
    levelCount: 5,
    challengeCount: 25,
    xpReward: 2500,
    estimatedHours: 8,
    levels: [
      { id: 'a1', title: 'Array Basics', description: 'Fundamental array operations', order: 1, challengeCount: 5, xpReward: 500, challenges: [], completed: false, locked: false },
      { id: 'a2', title: 'Two Pointers', description: 'Two-pointer technique', order: 2, challengeCount: 5, xpReward: 500, challenges: [], completed: false, locked: true },
      { id: 'a3', title: 'Sliding Window', description: 'Window-based patterns', order: 3, challengeCount: 5, xpReward: 500, challenges: [], completed: false, locked: true },
      { id: 'a4', title: 'Prefix Sums', description: 'Cumulative sum techniques', order: 4, challengeCount: 5, xpReward: 500, challenges: [], completed: false, locked: true },
      { id: 'a5', title: 'Advanced Arrays', description: 'Complex array problems', order: 5, challengeCount: 5, xpReward: 500, challenges: [], completed: false, locked: true },
    ],
  },
  {
    id: '2',
    title: 'Strings',
    slug: 'strings',
    description: 'String processing, pattern matching, and text manipulation algorithms.',
    icon: 'Type',
    color: 'from-green-500 to-emerald-500',
    difficulty: 'Beginner',
    levelCount: 5,
    challengeCount: 20,
    xpReward: 2000,
    estimatedHours: 7,
    levels: [
      { id: 's1', title: 'String Basics', description: 'Basic string operations', order: 1, challengeCount: 4, xpReward: 400, challenges: [], completed: false, locked: false },
      { id: 's2', title: 'Pattern Matching', description: 'Search and match patterns', order: 2, challengeCount: 4, xpReward: 400, challenges: [], completed: false, locked: true },
      { id: 's3', title: 'String Manipulation', description: 'Transform and edit strings', order: 3, challengeCount: 4, xpReward: 400, challenges: [], completed: false, locked: true },
      { id: 's4', title: 'Anagrams & Palindromes', description: 'Anagram and palindrome problems', order: 4, challengeCount: 4, xpReward: 400, challenges: [], completed: false, locked: true },
      { id: 's5', title: 'Advanced Strings', description: 'Complex string algorithms', order: 5, challengeCount: 4, xpReward: 400, challenges: [], completed: false, locked: true },
    ],
  },
  {
    id: '3',
    title: 'Sorting',
    slug: 'sorting',
    description: 'Compare, implement, and apply various sorting algorithms and techniques.',
    icon: 'ArrowUpDown',
    color: 'from-orange-500 to-red-500',
    difficulty: 'Intermediate',
    levelCount: 4,
    challengeCount: 16,
    xpReward: 2000,
    estimatedHours: 6,
    levels: [
      { id: 'so1', title: 'Basic Sorts', description: 'Bubble, selection, insertion sort', order: 1, challengeCount: 4, xpReward: 500, challenges: [], completed: false, locked: false },
      { id: 'so2', title: 'Divide & Conquer', description: 'Merge sort, quick sort', order: 2, challengeCount: 4, xpReward: 500, challenges: [], completed: false, locked: true },
      { id: 'so3', title: 'Linear Sorts', description: 'Counting, radix, bucket sort', order: 3, challengeCount: 4, xpReward: 500, challenges: [], completed: false, locked: true },
      { id: 'so4', title: 'Sorting Applications', description: 'Real-world sorting problems', order: 4, challengeCount: 4, xpReward: 500, challenges: [], completed: false, locked: true },
    ],
  },
  {
    id: '4',
    title: 'Searching',
    slug: 'searching',
    description: 'Linear search, binary search, and advanced search techniques.',
    icon: 'Search',
    color: 'from-purple-500 to-violet-500',
    difficulty: 'Beginner',
    levelCount: 4,
    challengeCount: 16,
    xpReward: 1800,
    estimatedHours: 5,
    levels: [
      { id: 'se1', title: 'Linear Search', description: 'Sequential search techniques', order: 1, challengeCount: 4, xpReward: 450, challenges: [], completed: false, locked: false },
      { id: 'se2', title: 'Binary Search', description: 'Divide and conquer search', order: 2, challengeCount: 4, xpReward: 450, challenges: [], completed: false, locked: true },
      { id: 'se3', title: 'Search Variants', description: 'Modified search algorithms', order: 3, challengeCount: 4, xpReward: 450, challenges: [], completed: false, locked: true },
      { id: 'se4', title: 'Search Applications', description: 'Complex search problems', order: 4, challengeCount: 4, xpReward: 450, challenges: [], completed: false, locked: true },
    ],
  },
  {
    id: '5',
    title: 'Dynamic Programming',
    slug: 'dynamic-programming',
    description: 'Master DP with memoization, tabulation, and classic problem patterns.',
    icon: 'GitBranch',
    color: 'from-pink-500 to-rose-500',
    difficulty: 'Advanced',
    levelCount: 6,
    challengeCount: 30,
    xpReward: 4000,
    estimatedHours: 15,
    levels: [
      { id: 'dp1', title: 'Introduction to DP', description: 'Basic DP concepts', order: 1, challengeCount: 5, xpReward: 650, challenges: [], completed: false, locked: false },
      { id: 'dp2', title: 'Knapsack Pattern', description: '0/1 and unbounded knapsack', order: 2, challengeCount: 5, xpReward: 650, challenges: [], completed: false, locked: true },
      { id: 'dp3', title: 'Sequence DP', description: 'LIS, LCS, edit distance', order: 3, challengeCount: 5, xpReward: 650, challenges: [], completed: false, locked: true },
      { id: 'dp4', title: 'Grid DP', description: 'Matrix path problems', order: 4, challengeCount: 5, xpReward: 650, challenges: [], completed: false, locked: true },
      { id: 'dp5', title: 'DP on Trees', description: 'Tree-based DP', order: 5, challengeCount: 5, xpReward: 700, challenges: [], completed: false, locked: true },
      { id: 'dp6', title: 'Advanced DP', description: 'Complex DP problems', order: 6, challengeCount: 5, xpReward: 700, challenges: [], completed: false, locked: true },
    ],
  },
  {
    id: '6',
    title: 'Graphs',
    slug: 'graphs',
    description: 'Graph traversals, shortest paths, MSTs, and network flow algorithms.',
    icon: 'Share2',
    color: 'from-indigo-500 to-blue-500',
    difficulty: 'Advanced',
    levelCount: 6,
    challengeCount: 24,
    xpReward: 3500,
    estimatedHours: 14,
    levels: [
      { id: 'g1', title: 'Graph Basics', description: 'Representations and traversals', order: 1, challengeCount: 4, xpReward: 580, challenges: [], completed: false, locked: false },
      { id: 'g2', title: 'BFS & DFS', description: 'Breadth and depth-first search', order: 2, challengeCount: 4, xpReward: 580, challenges: [], completed: false, locked: true },
      { id: 'g3', title: 'Shortest Paths', description: 'Dijkstra, Bellman-Ford, Floyd', order: 3, challengeCount: 4, xpReward: 580, challenges: [], completed: false, locked: true },
      { id: 'g4', title: 'MST & Union Find', description: 'Minimum spanning trees', order: 4, challengeCount: 4, xpReward: 580, challenges: [], completed: false, locked: true },
      { id: 'g5', title: 'Topological Sort', description: 'DAG processing', order: 5, challengeCount: 4, xpReward: 580, challenges: [], completed: false, locked: true },
      { id: 'g6', title: 'Advanced Graphs', description: 'Complex graph problems', order: 6, challengeCount: 4, xpReward: 600, challenges: [], completed: false, locked: true },
    ],
  },
  {
    id: '7',
    title: 'Trees',
    slug: 'trees',
    description: 'Binary trees, BSTs, tries, segment trees, and tree algorithms.',
    icon: 'GitFork',
    color: 'from-teal-500 to-green-500',
    difficulty: 'Intermediate',
    levelCount: 5,
    challengeCount: 20,
    xpReward: 2800,
    estimatedHours: 10,
    levels: [
      { id: 't1', title: 'Binary Trees', description: 'Tree traversals and operations', order: 1, challengeCount: 4, xpReward: 560, challenges: [], completed: false, locked: false },
      { id: 't2', title: 'Binary Search Trees', description: 'BST operations and properties', order: 2, challengeCount: 4, xpReward: 560, challenges: [], completed: false, locked: true },
      { id: 't3', title: 'Tree Traversals', description: 'Inorder, preorder, postorder', order: 3, challengeCount: 4, xpReward: 560, challenges: [], completed: false, locked: true },
      { id: 't4', title: 'Advanced Trees', description: 'AVL, Red-Black, Segment trees', order: 4, challengeCount: 4, xpReward: 560, challenges: [], completed: false, locked: true },
      { id: 't5', title: 'Trie', description: 'Prefix tree operations', order: 5, challengeCount: 4, xpReward: 560, challenges: [], completed: false, locked: true },
    ],
  },
  {
    id: '8',
    title: 'Greedy',
    slug: 'greedy',
    description: 'Greedy algorithms, interval scheduling, and optimization problems.',
    icon: 'Zap',
    color: 'from-yellow-500 to-amber-500',
    difficulty: 'Intermediate',
    levelCount: 4,
    challengeCount: 16,
    xpReward: 2000,
    estimatedHours: 6,
    levels: [
      { id: 'gr1', title: 'Greedy Basics', description: 'Fundamental greedy concepts', order: 1, challengeCount: 4, xpReward: 500, challenges: [], completed: false, locked: false },
      { id: 'gr2', title: 'Interval Problems', description: 'Interval scheduling and merging', order: 2, challengeCount: 4, xpReward: 500, challenges: [], completed: false, locked: true },
      { id: 'gr3', title: 'Optimization', description: 'Greedy optimization techniques', order: 3, challengeCount: 4, xpReward: 500, challenges: [], completed: false, locked: true },
      { id: 'gr4', title: 'Advanced Greedy', description: 'Complex greedy problems', order: 4, challengeCount: 4, xpReward: 500, challenges: [], completed: false, locked: true },
    ],
  },
  {
    id: '9',
    title: 'Recursion & Backtracking',
    slug: 'recursion-backtracking',
    description: 'Recursive thinking, backtracking, and combinatorial problem-solving.',
    icon: 'RotateCcw',
    color: 'from-cyan-500 to-blue-500',
    difficulty: 'Intermediate',
    levelCount: 4,
    challengeCount: 16,
    xpReward: 2200,
    estimatedHours: 8,
    levels: [
      { id: 'r1', title: 'Recursion Basics', description: 'Fundamental recursion patterns', order: 1, challengeCount: 4, xpReward: 550, challenges: [], completed: false, locked: false },
      { id: 'r2', title: 'Backtracking Intro', description: 'Basic backtracking', order: 2, challengeCount: 4, xpReward: 550, challenges: [], completed: false, locked: true },
      { id: 'r3', title: 'Permutations & Combinations', description: 'Combinatorial generation', order: 3, challengeCount: 4, xpReward: 550, challenges: [], completed: false, locked: true },
      { id: 'r4', title: 'Advanced Backtracking', description: 'Complex backtracking problems', order: 4, challengeCount: 4, xpReward: 550, challenges: [], completed: false, locked: true },
    ],
  },
  {
    id: '10',
    title: 'Bit Manipulation',
    slug: 'bit-manipulation',
    description: 'Bitwise operations, bit manipulation tricks, and binary number theory.',
    icon: 'Binary',
    color: 'from-fuchsia-500 to-purple-500',
    difficulty: 'Advanced',
    levelCount: 3,
    challengeCount: 12,
    xpReward: 1800,
    estimatedHours: 5,
    levels: [
      { id: 'b1', title: 'Bit Basics', description: 'Basic bitwise operations', order: 1, challengeCount: 4, xpReward: 600, challenges: [], completed: false, locked: false },
      { id: 'b2', title: 'Bit Tricks', description: 'Common bit manipulation patterns', order: 2, challengeCount: 4, xpReward: 600, challenges: [], completed: false, locked: true },
      { id: 'b3', title: 'Advanced Bit', description: 'Complex bit manipulation', order: 3, challengeCount: 4, xpReward: 600, challenges: [], completed: false, locked: true },
    ],
  },
  {
    id: '11',
    title: 'Math',
    slug: 'math',
    description: 'Number theory, combinatorics, geometry, and mathematical problem-solving.',
    icon: 'Sigma',
    color: 'from-sky-500 to-indigo-500',
    difficulty: 'Intermediate',
    levelCount: 4,
    challengeCount: 16,
    xpReward: 2000,
    estimatedHours: 7,
    levels: [
      { id: 'm1', title: 'Number Theory', description: 'Primes, GCD, modulo operations', order: 1, challengeCount: 4, xpReward: 500, challenges: [], completed: false, locked: false },
      { id: 'm2', title: 'Combinatorics', description: 'Counting and probability', order: 2, challengeCount: 4, xpReward: 500, challenges: [], completed: false, locked: true },
      { id: 'm3', title: 'Geometry', description: 'Computational geometry', order: 3, challengeCount: 4, xpReward: 500, challenges: [], completed: false, locked: true },
      { id: 'm4', title: 'Advanced Math', description: 'Complex math problems', order: 4, challengeCount: 4, xpReward: 500, challenges: [], completed: false, locked: true },
    ],
  },
];

export const SAMPLE_CHALLENGE = {
  id: 'ch1',
  title: 'Two Sum',
  slug: 'two-sum',
  difficulty: 'Easy' as const,
  estimatedTime: '15 min',
  points: 100,
  xpReward: 150,
  description: 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice.',
  story: 'The ancient library of Alexandria holds a mysterious cipher. Two specific scrolls, when combined, reveal the location of the hidden Chamber of Wisdom. As the lead cryptographer, you must find which two scrolls (by their positions) unlock the secret.',
  inputFormat: 'First line contains integer n (2 ≤ n ≤ 10^5). Second line contains n space-separated integers. Third line contains the target integer.',
  outputFormat: 'Output two space-separated integers representing the indices (0-based) of the two numbers that add up to target.',
  constraints: '2 ≤ nums.length ≤ 10^5\n-10^9 ≤ nums[i] ≤ 10^9\n-10^9 ≤ target ≤ 10^9\nOnly one valid answer exists.',
  examples: [
    { input: '4\n2 7 11 15\n9', output: '0 1', explanation: 'nums[0] + nums[1] = 2 + 7 = 9, so we return [0, 1].' },
    { input: '3\n3 2 4\n6', output: '1 2', explanation: 'nums[1] + nums[2] = 2 + 4 = 6, so we return [1, 2].' },
  ],
  notes: 'A naive O(n²) solution may timeout for large inputs. Try to solve it in O(n) time.',
  hints: ['What data structure gives you O(1) lookups?', 'Think about complement: target - nums[i]', 'As you iterate, check if the complement of the current number exists.'],
  allowedLanguages: ['Python', 'JavaScript', 'TypeScript', 'Java', 'C++', 'Go', 'Rust', 'C'],
  timeLimit: 1000,
  memoryLimit: 256,
  tags: ['Array', 'Hash Table'],
  completed: false,
  solved: false,
};

export const COMPETITIONS: Competition[] = [
  {
    id: 'comp1',
    title: 'Weekly Sprint #42',
    description: 'Solve 3 challenges in 90 minutes. Top 10 win exclusive badges.',
    startTime: '2026-07-25T00:00:00Z',
    endTime: '2026-07-25T01:30:00Z',
    challenges: ['two-sum', 'reverse-string', 'binary-search'],
    participants: 847,
    status: 'Upcoming',
    prizes: ['Gold Badge', '500 XP', 'Leaderboard Spotlight'],
  },
  {
    id: 'comp2',
    title: 'Monthly Algorithm Cup',
    description: 'A 6-hour competition with 8 challenges across all difficulty levels.',
    startTime: '2026-08-01T00:00:00Z',
    endTime: '2026-08-01T06:00:00Z',
    challenges: ['two-sum', 'merge-sort', 'dijkstra', 'lcs', 'n-queens'],
    participants: 2341,
    status: 'Upcoming',
    prizes: ['Champion Trophy', '2000 XP', '1 Year Pro Subscription'],
  },
  {
    id: 'comp3',
    title: 'DP Masters Challenge',
    description: 'All dynamic programming. 5 problems in 3 hours.',
    startTime: '2026-07-20T00:00:00Z',
    endTime: '2026-07-20T03:00:00Z',
    challenges: ['fibonacci', 'knapsack', 'lcs', 'edit-distance'],
    participants: 1204,
    status: 'Completed',
    prizes: ['DP Master Badge', '1000 XP'],
  },
];

export const ACHIEVEMENTS: Achievement[] = [
  { id: 'ach1', title: 'First Solve', description: 'Solved your first challenge', icon: 'Star', unlocked: true, unlockedAt: '2026-07-15' },
  { id: 'ach2', title: 'Speed Demon', description: 'Solved a challenge in under 5 minutes', icon: 'Zap', unlocked: true, unlockedAt: '2026-07-16' },
  { id: 'ach3', title: 'Bug Hunter', description: 'Found and fixed a bug in your code', icon: 'Bug', unlocked: true, unlockedAt: '2026-07-17' },
  { id: 'ach4', title: 'Perfect Submission', description: 'First try acceptance', icon: 'Target', unlocked: false },
  { id: 'ach5', title: '10 Solves', description: 'Solved 10 challenges', icon: 'Award', unlocked: true, unlockedAt: '2026-07-18' },
  { id: 'ach6', title: 'Daily Streak', description: 'Solved daily challenge for 7 days', icon: 'Flame', unlocked: false },
  { id: 'ach7', title: '100 Solves', description: 'Solved 100 challenges', icon: 'Trophy', unlocked: false },
  { id: 'ach8', title: 'Champion', description: 'Won a competition', icon: 'Crown', unlocked: false },
];

export const BADGES: Badge[] = [
  { id: 'badge1', title: 'Beginner', description: 'Started your journey', icon: 'Compass', color: 'from-gray-400 to-gray-300' },
  { id: 'badge2', title: 'Array Master', description: 'Completed Arrays track', icon: 'Layers', color: 'from-blue-400 to-cyan-300' },
  { id: 'badge3', title: 'DP Wizard', description: 'Completed DP track', icon: 'GitBranch', color: 'from-pink-400 to-rose-300' },
  { id: 'badge4', title: 'Speed Runner', description: 'Top 10 in a competition', icon: 'Timer', color: 'from-amber-400 to-orange-300' },
];

export const MOCK_USER: User = {
  id: 'user1',
  username: 'algomaster',
  email: 'algomaster@example.com',
  avatar: '',
  country: 'US',
  bio: 'Full-stack developer passionate about algorithms and competitive programming.',
  xp: 4520,
  level: 7,
  rank: 'Expert',
  solvedProblems: 42,
  winStreak: 5,
  accuracy: 87,
  favoriteLanguage: 'Python',
  createdAt: '2026-01-15',
};

export const MOCK_DASHBOARD: DashboardStats = {
  totalXp: 4520,
  level: 7,
  rank: 'Expert',
  leaderboardPosition: 128,
  solvedChallenges: 42,
  totalChallenges: 156,
  winStreak: 5,
  accuracy: 87,
  currentTrack: TRACKS[0],
  currentChallenge: SAMPLE_CHALLENGE,
  dailyChallenge: { ...SAMPLE_CHALLENGE, title: 'Reverse String', slug: 'reverse-string' },
  recentSubmissions: [
    { id: 'sub1', userId: 'user1', challengeId: 'ch1', code: '', language: 'Python', status: 'Accepted', runtime: 45, memory: 16.2, passedTests: 5, totalTests: 5, createdAt: '2026-07-21T10:30:00Z' },
    { id: 'sub2', userId: 'user1', challengeId: 'ch2', code: '', language: 'Python', status: 'Wrong Answer', runtime: 32, memory: 14.8, passedTests: 3, totalTests: 5, createdAt: '2026-07-21T09:15:00Z' },
    { id: 'sub3', userId: 'user1', challengeId: 'ch3', code: '', language: 'JavaScript', status: 'Accepted', runtime: 52, memory: 18.1, passedTests: 6, totalTests: 6, createdAt: '2026-07-20T22:00:00Z' },
    { id: 'sub4', userId: 'user1', challengeId: 'ch4', code: '', language: 'Python', status: 'Time Limit Exceeded', runtime: 2005, memory: 20.3, passedTests: 4, totalTests: 6, createdAt: '2026-07-20T18:45:00Z' },
    { id: 'sub5', userId: 'user1', challengeId: 'ch5', code: '', language: 'Rust', status: 'Accepted', runtime: 12, memory: 8.4, passedTests: 4, totalTests: 4, createdAt: '2026-07-19T14:00:00Z' },
  ],
  achievements: ACHIEVEMENTS,
  badges: BADGES,
};

export const LEADERBOARD_DATA = [
  { rank: 1, userId: 'u1', username: 'code_ninja', avatar: '', xp: 15200, solvedProblems: 142, accuracy: 96, winStreak: 42 },
  { rank: 2, userId: 'u2', username: 'algo_wizard', avatar: '', xp: 14800, solvedProblems: 138, accuracy: 94, winStreak: 35 },
  { rank: 3, userId: 'u3', username: 'byte_breaker', avatar: '', xp: 13100, solvedProblems: 125, accuracy: 91, winStreak: 28 },
  { rank: 4, userId: 'u4', username: 'data_structure', avatar: '', xp: 12000, solvedProblems: 118, accuracy: 93, winStreak: 21 },
  { rank: 5, userId: 'u5', username: 'runtime_error', avatar: '', xp: 11500, solvedProblems: 110, accuracy: 85, winStreak: 7 },
  { rank: 6, userId: 'u6', username: 'stack_overflow', avatar: '', xp: 10800, solvedProblems: 105, accuracy: 89, winStreak: 14 },
  { rank: 7, userId: 'u7', username: 'segfault', avatar: '', xp: 10200, solvedProblems: 98, accuracy: 82, winStreak: 10 },
  { rank: 8, userId: 'u8', username: 'null_pointer', avatar: '', xp: 9800, solvedProblems: 92, accuracy: 88, winStreak: 5 },
  { rank: 9, userId: 'u9', username: 'infinite_loop', avatar: '', xp: 9200, solvedProblems: 88, accuracy: 79, winStreak: 3 },
  { rank: 10, userId: 'u10', username: 'algomaster', avatar: '', xp: 4520, solvedProblems: 42, accuracy: 87, winStreak: 5 },
];

export const LANGUAGES = [
  { value: 'python', label: 'Python', extension: 'py', monaco: 'python' },
  { value: 'javascript', label: 'JavaScript', extension: 'js', monaco: 'javascript' },
  { value: 'typescript', label: 'TypeScript', extension: 'ts', monaco: 'typescript' },
  { value: 'java', label: 'Java', extension: 'java', monaco: 'java' },
  { value: 'cpp', label: 'C++', extension: 'cpp', monaco: 'cpp' },
  { value: 'go', label: 'Go', extension: 'go', monaco: 'go' },
  { value: 'rust', label: 'Rust', extension: 'rs', monaco: 'rust' },
  { value: 'c', label: 'C', extension: 'c', monaco: 'c' },
];

export const ALL_TRACKS_LIST = TRACKS.map(t => ({
  value: t.slug,
  label: t.title,
}));
